import './globals.css'
import Link from "next/link";


export const metadata = {
  title: 'Web Tutorial',
  description: 'Generated by create next app',
}

// npx json-server --port 9999 --watch db.json

export default async function RootLayout({ children }) {
        //const resp = await fetch('http://localhost:9999/topics', { next : {revalidate : 0}});
        const resp = await fetch('http://localhost:9999/topics', { cache : "no-store"});
        const topics = await resp.json();
  return (
    <html lang="en">
      <body>
      <h1><Link href="">WEB</Link></h1>
      <ol>
          {topics.map((topic) => {
              return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}, {topic.body}</Link></li>

          })}
      </ol>
      {children}
      <ul>
          <li><Link href="/create">create</Link></li>
          <li><Link href="/update/1">update</Link></li>
          <li><input type="button" value="delete" /></li>
      </ul>
      </body>
    </html>
  )
}
