import './globals.css'


export const metadata = {
  title: 'Web Tutorial',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <h1><a href="">WEB</a></h1>
      <ol>
          <li><a href="/read/1">html</a></li>
          <li><a href="/read/2">css</a></li>
      </ol>
      {children}
      <ul>
          <li><a href="/create">create</a></li>
          <li><a href="/update/1">update</a></li>
          <li><input type="button" value="delete" /></li>
      </ul>
      </body>
    </html>
  )
}
